from rocrate.rocrate import ROCrate
from datetime import date
from src.validate_project import validate_project
import sys

print(sys.executable)

if not validate_project():
    raise SystemExit(
        "Cannot build RO-Crate because required project files are missing.")

crate = ROCrate()

crate.name = "Executable SSH Research Workflow"
crate.description = "Example SSH workflow packaged as an RO-Crate for reproducible SSH research."

crate.root_dataset["license"] = "https://spdx.org/licenses/MIT.html"
crate.root_dataset["datePublished"] = date.today().isoformat()

# README
readme = crate.add_file(
    "README.md",
    properties={
        "@type": "File",
        "name": "Project README",
        "description": "Human-readable documentation for the executable SSH workflow crate."
    }
)

# Dataset
dataset = crate.add_file(
    "data/speeches.csv",
    properties={
        "@type": "Dataset",
        "name": "Speech dataset",
        "description": "Example SSH text dataset used for analysis.",
        "encodingFormat": "text/csv"
    }
)

# Python workflow script
workflow = crate.add_file(
    "src/analyze.py",
    properties={
        "@type": "SoftwareSourceCode",
        "name": "Text analysis workflow",
        "description": "Python script for SSH text analysis.",
        "programmingLanguage": "Python",
        "runtimePlatform": "Python 3",
    }
)

# Notebook
notebook = crate.add_file(
    "notebooks/analysis.ipynb",
    properties={
        "@type": "ComputationalWorkflow",
        "name": "Analysis notebook",
        "description": "Jupyter notebook demonstrating the workflow."
    }
)

# Environment specification
environment = crate.add_file(
    "environment.yml",
    properties={
        "@type": "File",
        "name": "Execution environment",
        "description": "Conda environment specification.",
        "encodingFormat": "text/yaml"
    }
)

# CodeMeta metadata
codemeta = crate.add_file(
    "codemeta.json",
    properties={
        "@type": "CreativeWork",
        "name": "CodeMeta metadata"
    }
)

# Vocabulary
vocab = crate.add_file(
    "vocab/vocab.ttl",
    properties={
        "@type": "File",
        "name": "Multilingual SSH vocabulary"
    }
)

# Output dataset
output = crate.add_file(
    "outputs/word_counts.csv",
    properties={
        "@type": "Dataset",
        "name": "Word frequency results",
        "description": "Output dataset generated by the text analysis workflow."
    }
)

# Execution provenance log
provenance_log = crate.add_file(
    "logs/execution_log.json",
    properties={
        "@type": "File",
        "name": "Execution provenance log",
        "description": "Record of workflow execution including timestamp, Python environment, input, and output."
    }
)

# Workflow relationships
workflow["input"] = dataset
workflow["output"] = output
workflow["softwareRequirements"] = environment

notebook["isBasedOn"] = workflow
output["isBasedOn"] = dataset
provenance_log["about"] = workflow

crate.write("ssh_workflow_crate")

print("RO-Crate with workflow relationships, notebook, vocabulary, README, and provenance log created successfully.")
